POST http://localhost:4040/generate-text
Content-Type: application/json

{
    "prompt":"summer in switzerland",
    "subprompts":[
        "iphone vs android",
    "how to choose the right iphone vs android",
    "when is the last time you compared an android to an iphone",
    "what is the difference between an android and an iphone?",
    "where is the difference between an android and an iphone"
    ]
}