POST http://localhost:4040/generate-text
Content-Type: application/json

{
    "prompt": "how to live life?",
  "subprompts": [
    "how to live a life of love in the real world?",
    "how to live a life of love?",
    "how to live a happy life?",
    "how to live a life of love in a city?",
    "what is life like?",
    "where is life?",
    "i love you but i dont know if you have a life like this?"
  ]
}